src/main/java/cz/upol/inf/vanusanik/ministag/schedule/ScheduleServlet.java
package cz.upol.inf.vanusanik.ministag.schedule;

import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * ScheduleServlet.
 * 
 * Handles all requests to draw schedule image. Only responds to /draw request.
 * 
 * Example usage syntax:
 * 
 * /draw?width=800&amp;height=400&amp;encoding=png
 * /draw?width=800&amp;height=400&amp;encoding=jpg
 * /draw?width=800&amp;height=400&amp;encoding=gif
 * 
 * @author enerccio
 *
 */
public class ScheduleServlet extends HttpServlet {
	private static final long serialVersionUID = 5850204032730392319L;

	public static final String URI = "/draw";
	public static final String WIDTH = "width";
	public static final String HEIGHT = "height";
	public static final String ENCODING = "encoding";

	@Inject
	private ImageOutputWriter outputWriter;
	@Inject
	private ScheduleGenerator outputGenerator;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		if (req.getPathInfo() == null || !req.getPathInfo().equals(URI)) {
			resp.sendError(HttpServletResponse.SC_NOT_FOUND);
			return;
		}

		resp.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
		resp.setHeader("Pragma", "no-cache");
		resp.setDateHeader("Expires", 0);

		String strw = req.getParameter(WIDTH);
		String strh = req.getParameter(HEIGHT);
		String encoding = req.getParameter(ENCODING);

		if (strw == null || strh == null || encoding == null) {
			resp.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		}

		int w, h;
		try {
			w = Integer.parseInt(strw);
			h = Integer.parseInt(strh);
		} catch (NumberFormatException e) {
			resp.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		}

		if (w == 0 || h == 0) {
			resp.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		}

		try {
			BufferedImage i = outputGenerator.generate(w, h);
			outputWriter.generate(i, encoding, resp);
		} catch (Exception e) {
			throw new ServletException(e);
		}
	}

}

src/main/java/cz/upol/inf/vanusanik/ministag/ui/services/DepartmentController.java
package cz.upol.inf.vanusanik.ministag.ui.services;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import cz.upol.inf.vanusanik.ministag.model.entities.Department;
import cz.upol.inf.vanusanik.ministag.model.entities.Roles;
import cz.upol.inf.vanusanik.ministag.model.entities.User;
import cz.upol.inf.vanusanik.ministag.model.service.MinistagRepository;
import cz.upol.inf.vanusanik.ministag.ui.tools.Utils;

/**
 * DepartmentController
 * 
 * @author enerccio
 *
 */
@Named("departmentController")
@ApplicationScoped
public class DepartmentController {

	/**
	 * Holds active department for session
	 * 
	 * @author enerccio
	 *
	 */
	@Named("activeDepartment")
	@SessionScoped
	public static class ActiveDepartment implements Serializable {
		private static final long serialVersionUID = -1751329860707450138L;

		private String activeDepartment;

		public String getActiveDepartment() {
			return activeDepartment;
		}

		public void setActiveDepartment(String activeDepartment) {
			this.activeDepartment = activeDepartment;
		}

	}

	/**
	 * Holds active departments for session
	 * 
	 * @author enerccio
	 *
	 */
	@Named("departmentList")
	@RequestScoped
	public static class DepartmentList {

		@Inject
		private DepartmentController controller;

		public List<Department> getDepartments() {
			return controller.getDepartments();
		}

		public String edit(String dept) {
			if ("".equals(dept))
				dept = null;
			return controller.editDepartment(dept);
		}

		public String remove(String dept) {
			controller.removeDepartments(dept);
			return Utils.appendRedirect("admDept.xhtml");
		}
	}

	/**
	 * Handles requests to edit department
	 * 
	 * @author enerccio
	 *
	 */
	@Named("editDepartment")
	@RequestScoped
	public static class EditDepartment {

		@Inject
		private ActiveDepartment ad;
		@Inject
		private MinistagRepository repository;
		@Inject
		private DepartmentController controller;

		private String abbr;
		private String desc;
		private String name;
		private List<String> garants;
		private List<String> teachers;

		@PostConstruct
		public void init() {
			if (ad.getActiveDepartment() != null) {
				Department d = repository.find(ad.getActiveDepartment(), Department.class);
				abbr = d.getShortName();
				desc = d.getDescription();
				name = d.getName();
				garants = new ArrayList<String>();
				teachers = new ArrayList<String>();

				for (User u : d.getGarants()) {
					garants.add(u.getLogin());
				}

				for (User u : d.getTeachers()) {
					teachers.add(u.getLogin());
				}
			}
		}

		public List<User> getAllGarants() {
			return repository.getUsersByRole(Roles.GARANT);
		}

		public List<User> getAllTeachers() {
			List<User> ul = new ArrayList<User>(repository.getUsersByRole(Roles.GARANT));
			ul.addAll(repository.getUsersByRole(Roles.TEACHER));
			return ul;
		}

		public ActiveDepartment getAd() {
			return ad;
		}

		public void setAd(ActiveDepartment ad) {
			this.ad = ad;
		}

		public String getAbbr() {
			return abbr;
		}

		public void setAbbr(String abbr) {
			this.abbr = abbr;
		}

		public String getDesc() {
			return desc;
		}

		public void setDesc(String desc) {
			this.desc = desc;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public List<String> getGarants() {
			return garants;
		}

		public void setGarants(List<String> garants) {
			this.garants = garants;
		}

		public List<String> getTeachers() {
			return teachers;
		}

		public void setTeachers(List<String> teachers) {
			this.teachers = teachers;
		}

		public String submit() {
			return controller.editDepartment(this);
		}
	}

	@Inject
	private MinistagRepository repository;
	@Inject
	private ActiveDepartment activeDepartment;

	public List<Department> getDepartments() {
		return repository.getDepartments();
	}

	/**
	 * Actually edits the department specified. Called on submit.
	 * 
	 * @param editDepartment
	 * @return
	 */
	public String editDepartment(EditDepartment editDepartment) {
		Department d = null;
		if (activeDepartment.getActiveDepartment() != null) {
			d = repository.find(activeDepartment.getActiveDepartment(), Department.class);
		} else {
			d = new Department();
		}

		d.setShortName(editDepartment.getAbbr());
		d.setName(editDepartment.getName());
		d.setDescription(editDepartment.getDesc());
		d.getGarants().clear();
		for (String g : editDepartment.getGarants()) {
			User u = repository.find(g, User.class);
			d.getGarants().add(u);
		}
		d.getTeachers().clear();
		for (String g : editDepartment.getTeachers()) {
			User u = repository.find(g, User.class);
			d.getTeachers().add(u);
		}

		repository.save(d);

		return Utils.appendRedirect("admDept.xhtml");
	}

	public void removeDepartments(String dept) {
		repository.remove(repository.find(dept, Department.class));
	}

	/**
	 * Selects which department is to be edited and then redirects to edit page
	 * 
	 * @param dept
	 * @return
	 */
	public String editDepartment(String dept) {
		activeDepartment.setActiveDepartment(dept);
		return Utils.appendRedirect("admEditDept.xhtml");
	}

}

src/main/java/cz/upol/inf/vanusanik/ministag/ui/services/GarantController.java
package cz.upol.inf.vanusanik.ministag.ui.services;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import cz.upol.inf.vanusanik.ministag.model.entities.Course;
import cz.upol.inf.vanusanik.ministag.model.entities.Department;
import cz.upol.inf.vanusanik.ministag.model.entities.EndingType;
import cz.upol.inf.vanusanik.ministag.model.entities.RequiredBlock;
import cz.upol.inf.vanusanik.ministag.model.entities.Timetable;
import cz.upol.inf.vanusanik.ministag.model.entities.TimetableType;
import cz.upol.inf.vanusanik.ministag.model.entities.User;
import cz.upol.inf.vanusanik.ministag.model.service.MinistagRepository;
import cz.upol.inf.vanusanik.ministag.ui.services.SecurityController.ActiveSession;
import cz.upol.inf.vanusanik.ministag.ui.tools.Utils;

/**
 * GarantController
 * 
 * @author enerccio
 *
 */
@ApplicationScoped
@Named("garant")
public class GarantController {

	@Inject
	private ActiveSession as;
	@Inject
	private MinistagRepository repository;
	@Inject
	private ChosenDepartment ad;
	@Inject
	private ChosenCourse ac;
	@Inject
	private ChosenBlock ab;
	@Inject
	private GarantEditBlock eb;

	/**
	 * Holds currenly chosen department for session
	 * 
	 * @author enerccio
	 *
	 */
	@SessionScoped
	@Named("garantChosenDept")
	public static class ChosenDepartment implements Serializable {
		private static final long serialVersionUID = 8978334012055233297L;

		private Department currentDepartment;

		public Department getCurrentDepartment() {
			return currentDepartment;
		}

		public void setCurrentDepartment(Department currentDepartment) {
			this.currentDepartment = currentDepartment;
		}
	}

	/**
	 * Holds currently chosen course for session
	 * 
	 * @author enerccio
	 *
	 */
	@SessionScoped
	@Named("garantChosenCourse")
	public static class ChosenCourse implements Serializable {
		private static final long serialVersionUID = 8978334012055233298L;

		private Course currentCourse;

		public Course getCurrentCourse() {
			return currentCourse;
		}

		public void setCurrentCourse(Course currentCourse) {
			this.currentCourse = currentCourse;
		}
	}

	/**
	 * Holds currently chosen block for session
	 * 
	 * @author enerccio
	 *
	 */
	@SessionScoped
	@Named("garantChosenBlock")
	public static class ChosenBlock implements Serializable {
		private static final long serialVersionUID = 7978334012055233298L;

		private RequiredBlock currentBlock;

		public RequiredBlock getCurrentBlock() {
			return currentBlock;
		}

		public void setCurrentBlock(RequiredBlock currentBlock) {
			this.currentBlock = currentBlock;
		}
	}

	/**
	 * Handles showing department list
	 * 
	 * @author enerccio
	 *
	 */
	@RequestScoped
	@Named("garantDeptList")
	public static class GarantDepartmentList {

		@Inject
		private GarantController controller;

		public List<Department> getDepartments() {
			return controller.listDepartments();
		}

	}

	/**
	 * Handles editing the course
	 * 
	 * @author enerccio
	 *
	 */
	@RequestScoped
	@Named("garantCourseEdit")
	public static class GarantEditCourse {
		@Inject
		private GarantController controller;
		@Inject
		private ChosenCourse ac;
		@Inject
		private ChosenDepartment ad;
		@Inject
		private MinistagRepository repository;

		private String abbr = "";
		private String name = "";
		private User garant;
		private String description = "";
		private String syllabus = "";
		private int creditCount = 0;
		private EndingType endingType = EndingType.CREDIT;
		private boolean exam = false;

		@PostConstruct
		public void init() {
			controller.initEditCourse(this);
		}

		public String getAbbr() {
			return abbr;
		}

		public void setAbbr(String abbr) {
			this.abbr = abbr;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public User getGarant() {
			return garant;
		}

		public void setGarant(User garant) {
			this.garant = garant;
		}

		public String getDescription() {
			return description;
		}

		public void setDescription(String description) {
			this.description = description;
		}

		public String getSyllabus() {
			return syllabus;
		}

		public void setSyllabus(String syllabus) {
			this.syllabus = syllabus;
		}

		public int getCreditCount() {
			return creditCount;
		}

		public void setCreditCount(int creditCount) {
			this.creditCount = creditCount;
		}

		public EndingType getEndingType() {
			return endingType;
		}

		public void setEndingType(EndingType endingType) {
			this.endingType = endingType;
		}

		public boolean isExam() {
			return exam;
		}

		public void setExam(boolean exam) {
			this.exam = exam;
		}

		public List<EndingType> getEndings() {
			return new ArrayList<EndingType>(Arrays.asList(EndingType.values()));
		}

		public String submit() {
			Course c;
			boolean newCourse = false;
			if (ac.getCurrentCourse() != null) {
				c = repository.find(ac.getCurrentCourse().getId(), Course.class);
			} else {
				c = new Course();
				c.setDept(ad.getCurrentDepartment());
				newCourse = true;
			}

			c.setShortName(getAbbr());
			c.setCreditCount(getCreditCount());
			c.setDescription(getDescription());
			c.setEndingType(getEndingType());
			c.setGarant(getGarant());
			c.setHasExam(isExam());
			c.setName(getName());
			c.setSyllabus(getSyllabus());

			ac.setCurrentCourse(repository.save(c));

			if (newCourse) {
				Department d = repository.find(ad.getCurrentDepartment().getShortName(), Department.class);
				d.getCourses().add(ac.getCurrentCourse());

				ad.setCurrentDepartment(repository.save(d));
			}
			return Utils.appendRedirect("gmyCourses.xhtml");
		}
	}

	/**
	 * Handles editing block
	 * 
	 * @author enerccio
	 *
	 */
	@SessionScoped
	@Named("garantEditBlock")
	public static class GarantEditBlock implements Serializable {
		private static final long serialVersionUID = -8455586560856921293L;

		@Inject
		private ChosenCourse ac;
		@Inject
		private ChosenDepartment ad;
		@Inject
		private ChosenBlock ab;
		@Inject
		private MinistagRepository repository;
		@Inject
		private ActiveSession as;

		private String blockId = "";
		private String courseName = "";
		private List<Timetable> timetables = new ArrayList<Timetable>();

		private List<Timetable> timetables2delete = new ArrayList<Timetable>();

		private String teacher;
		private TimetableType type = TimetableType.LECTURE;
		private Date classFrom = Utils.calendarData(8, 0);
		private Date classTo = Utils.calendarData(9, 45);
		private int day = 0;

		@PostConstruct
		public void init() {
			teacher = as.getCurrentUser().getLogin();
			courseName = ad.getCurrentDepartment().getShortName() + "/" + ac.getCurrentCourse().getShortName();
			timetables.clear();
			timetables2delete.clear();
			if (ab.getCurrentBlock() != null) {
				timetables.clear();
				timetables.addAll(ab.getCurrentBlock().getTimetableChoices());
				blockId = ab.getCurrentBlock().getBlockDisplayName();
			}
		}

		public String submit() {
			RequiredBlock rb;
			if (ab.getCurrentBlock() == null) {
				rb = new RequiredBlock();
			} else {
				rb = ab.getCurrentBlock();
			}
			rb.setBlockDisplayName(getBlockId());
			rb.setTaughtClass(ac.getCurrentCourse());
			rb = repository.save(rb);

			ac.getCurrentCourse().getBlocks().add(rb);
			ac.setCurrentCourse(repository.save(ac.getCurrentCourse()));

			for (Timetable td : timetables2delete) {
				if (td.getBlock() != null) {
					rb.getTimetableChoices().remove(td);
					repository.remove(td);
				}
			}

			for (Timetable td : timetables) {
				if (td.getBlock() == null) {
					td.setBlock(rb);
					td = repository.save(td);
					rb.getTimetableChoices().add(td);
				} else {
					repository.save(td);
				}
			}

			ab.setCurrentBlock(repository.save(rb));
			init();
			return Utils.appendRedirect("gmyCourses.xhtml");
		}

		/**
		 * Adds single timetable entry. This is not saved until submit.
		 * 
		 * @return
		 */
		public String add() {
			Timetable t = new Timetable();
			t.setClassFrom(getClassFrom());
			t.setClassTo(getClassTo());
			t.setTeacher(repository.find(getTeacher(), User.class));
			t.setType(getType());
			t.setDay(getDay());
			timetables.add(t);

			type = TimetableType.LECTURE;
			teacher = null;
			classFrom = Utils.calendarData(8, 0);
			classTo = Utils.calendarData(9, 45);
			return "";
		}

		public String modify(Timetable t) {
			return "";
		}

		public String delete(Timetable t) {
			timetables2delete.add(t);
			timetables.remove(t);
			return "";
		}

		public String getBlockId() {
			return blockId;
		}

		public void setBlockId(String blockId) {
			this.blockId = blockId;
		}

		public String getCourseName() {
			return courseName;
		}

		public void setCourseName(String courseName) {
			this.courseName = courseName;
		}

		public List<Timetable> getTimetables() {
			return timetables;
		}

		public void setTimetables(List<Timetable> timetables) {
			this.timetables = timetables;
		}

		public String getTeacher() {
			return teacher;
		}

		public void setTeacher(String teacher) {
			this.teacher = teacher;
		}

		public TimetableType getType() {
			return type;
		}

		public void setType(TimetableType type) {
			this.type = type;
		}

		public Date getClassFrom() {
			return classFrom;
		}

		public void setClassFrom(Date classFrom) {
			this.classFrom = classFrom;
		}

		public Date getClassTo() {
			return classTo;
		}

		public void setClassTo(Date classTo) {
			this.classTo = classTo;
		}

		public List<TimetableType> getTimetableTypes() {
			return new ArrayList<TimetableType>(Arrays.asList(TimetableType.values()));
		}

		public List<User> getAllTeachers() {
			return ad.getCurrentDepartment().getTeachers();
		}

		public int getDay() {
			return day;
		}

web/admEditDept.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
    </h:head>
    <body>
        <ui:composition template="./templates/masterTemplate.xhtml">

            <ui:define name="top">
                <ui:include src="./templates/commonMenu.xhtml "/>
            </ui:define>

            <ui:define name="content">
          		<h:form>
	                <h:panelGrid columns="2">
	                    <h:outputLabel for="abbr">Zkratka katedry:</h:outputLabel>
	                    <h:inputText id="abbr" 
	                    	value="#{editDepartment.abbr}" >
	                    	<f:validator validatorId="GUARDNotEmpty" />
	                    	<f:validator binding="#{GUARDDeptAbbr}" />
	                    </h:inputText>
	                    
	                    <h:outputLabel for="abbr">Název katedry:</h:outputLabel>
	                    <h:inputText id="name" 
	                    	value="#{editDepartment.name}" >
	                    	<f:validator validatorId="GUARDNotEmpty" />
	                    </h:inputText>
	                    
	                    <h:outputLabel for="desc">Popis katedry:</h:outputLabel>
	                    <h:inputTextarea id="desc" 
	                    	value="#{editDepartment.desc}" rows="8">
	                    </h:inputTextarea>
	                    
	                    <h:outputLabel for="garants">Garanti:</h:outputLabel>
	                    <h:selectManyListbox value="#{editDepartment.garants}" id="garants">
				   			<f:selectItems value="#{editDepartment.allGarants}" var="u"
				   				itemLabel="#{u.name} ( #{u.login} )" itemValue="#{u.login}" />
				   		</h:selectManyListbox>
				   		
				   		<h:outputLabel for="teachers">Učitelé:</h:outputLabel>
	                    <h:selectManyListbox value="#{editDepartment.teachers}" id="teachers">
				   			<f:selectItems value="#{editDepartment.allTeachers}" var="u"
				   				itemLabel="#{u.name} ( #{u.login} )" itemValue="#{u.login}" />
				   		</h:selectManyListbox>
	                </h:panelGrid>
	                
	                <h:messages style="color:red;" showDetail="true"/>
			        <h:commandButton  value="Uložit" action="#{editDepartment.submit()}"/>
	            </h:form>
            </ui:define>

        </ui:composition>
    </body>
</html>

web/gTimetable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:my="http://java.sun.com/jsf/composite/components">
    <h:head>
    </h:head>
    <body>
        <ui:composition template="./templates/masterTemplate.xhtml">
        
        	<ui:define name="meta">
        		<c:if test="${garantChosenDept.currentDepartment == null}">
        			<meta http-equiv="refresh" content="0;url=gmyDept.xhtml" />
        		</c:if>
        		<c:if test="${garantChosenCourse.currentCourse == null}">
        			<meta http-equiv="refresh" content="0;url=gmyDept.xhtml" />
        		</c:if>
        	</ui:define>

            <ui:define name="top">
                <ui:include src="./templates/commonMenu.xhtml "/>
            </ui:define>

            <ui:define name="content">
          		<h:form>
	                <h:panelGrid columns="2">
	                    <h:outputLabel for="name">Název bloku:</h:outputLabel>
	                    <h:inputText id="name" 
	                    	value="#{garantEditBlock.blockId}" >
	                    	<f:validator validatorId="GUARDNotEmpty" />
	                    </h:inputText>
	                    
	                    <h:outputLabel for="course">Předmět:</h:outputLabel>
	                    <h:outputLabel id="course">#{garantEditBlock.courseName}</h:outputLabel>
	                    
	                    <h:outputLabel for="tt">Časové plány:</h:outputLabel>
	                    <h:dataTable id="tt" value="#{garantEditBlock.timetables}" var="t">
			          		<h:column>
			          			<f:facet name="header">Typ</f:facet>				          			
			          			<h:selectOneMenu value="#{t.type}">
							        <f:selectItems value="#{garantEditBlock.timetableTypes}" var="ttype"
							                       itemLabel="#{utils.timetableType2Display(ttype)}" 
							                       itemValue="#{ttype}" />
							    </h:selectOneMenu>
			          		</h:column>
			          		
			          		<h:column>
			          			<f:facet name="header">Vyučující</f:facet>
			          			<h:selectOneMenu value="#{t.teacher}" converter="#{ConverterUser}">
							        <f:selectItems value="#{garantEditBlock.allTeachers}" var="teacher"
							                       itemLabel="#{teacher.name}" 
							                       itemValue="#{teacher}" />
							    </h:selectOneMenu>
			          		</h:column>
			          		
			          		<h:column>
			          			<f:facet name="header">Den</f:facet>
			          			<h:selectOneMenu value="#{t.day}">
							        <f:selectItems value="#{utils.allDays}" var="d"
							                       itemLabel="#{utils.day2display(d)}" 
							                       itemValue="#{d}" />
							    </h:selectOneMenu>
			          		</h:column>
			          		
			          		<h:column>
			          			<f:facet name="header">Od</f:facet>
			          			<my:inputTime value="#{t.classFrom}" />
			          		</h:column>
			          		
			          		<h:column>
			          			<f:facet name="header">Do</f:facet>
			          			<my:inputTime value="#{t.classTo}" />
			          		</h:column>
			          		      		
			          		<h:column>
			    				<h:commandButton  value="Upravit" action="#{garantEditBlock.modify(t)}"/>
			          		</h:column>      		
			          		
			          		<h:column>
			    				<h:commandButton  value="Odstranit" action="#{garantEditBlock.delete(t)}"/>
			          		</h:column>
			          	</h:dataTable>
			          	
			          	<h:outputLabel for="ttadd">Časové plány - přidat:</h:outputLabel>
		        		<h:panelGrid id="ttadd" columns="2">
		        			<h:outputLabel for="timetabletype">Typ:</h:outputLabel>
		        			<h:selectOneMenu id="timetabletype" value="#{garantEditBlock.type}">
						        <f:selectItems value="#{garantEditBlock.timetableTypes}" var="ttype"
						                       itemLabel="#{utils.timetableType2Display(ttype)}" 
						                       itemValue="#{ttype}" />
						    </h:selectOneMenu>
						    
						    <h:outputLabel for="timetableteacher">Učitel:</h:outputLabel>
						    <h:selectOneMenu id="timetableteacher" value="#{garantEditBlock.teacher}">
						        <f:selectItems value="#{garantEditBlock.allTeachers}" var="teacher"
						                       itemLabel="#{teacher.name}" 
						                       itemValue="#{teacher.login}" />
						    </h:selectOneMenu>
						    
						    <h:outputLabel for="timetableday">Den:</h:outputLabel>
		          			<h:selectOneMenu id="timetableday" value="#{garantEditBlock.day}">
						        <f:selectItems value="#{utils.allDays}" var="d"
						                       itemLabel="#{utils.day2display(d)}" 
						                       itemValue="#{d}" />
						    </h:selectOneMenu>
						    
						    <h:outputLabel for="ttablefrom">Čas od:</h:outputLabel>
						    <my:inputTime id="ttablefrom" value="#{garantEditBlock.classFrom}" />
						    
						    <h:outputLabel for="ttableto">Čas do:</h:outputLabel>
						    <my:inputTime id="ttableto" value="#{garantEditBlock.classTo}" />
			        	</h:panelGrid>
			        	<h:outputLabel for="ttaddb"></h:outputLabel>
			        	<h:commandButton id="ttaddb" value="Přidat" action="#{garantEditBlock.add()}"/>
			        	 
	                </h:panelGrid>
	                
	                <c:if test="#{garantEditBlock.ab.currentBlock != null}">
						<div><img src="#{schedulerController.showSchedule(garantEditBlock.ab.currentBlock, 800, 400, 'png')}" /></div>
					</c:if>
	                
	                <h:messages style="color:red;" showDetail="true"/>
			        <h:commandButton  value="Uložit" action="#{garantEditBlock.submit()}"/>
	            </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>